# ── Overplanned Cloud Build — build + deploy to Cloud Run ─────────────
# Triggered on push to main. Builds web service, pushes to Artifact
# Registry, deploys to Cloud Run (public).
# ──────────────────────────────────────────────────────────────────────

substitutions:
  _REGION: us-central1
  _REPO: overplanned
  _WEB_SERVICE: overplanned-web
  _WEB_MIN_INSTANCES: '0'
  _WEB_MAX_INSTANCES: '10'

steps:
  # ── Run tests ──
  - id: test-web
    name: node:20
    waitFor: ['-']
    entrypoint: bash
    args:
      - -c
      - cd apps/web && npm ci && npx vitest run --exclude '.claude/**'

  # ── Build web image ──
  - id: build-web
    name: gcr.io/cloud-builders/docker
    waitFor: ['test-web']
    args:
      - build
      - -f
      - Dockerfile.web
      - -t
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_WEB_SERVICE}:${SHORT_SHA}'
      - -t
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_WEB_SERVICE}:latest'
      - .

  # ── Push web image ──
  - id: push-web
    name: gcr.io/cloud-builders/docker
    waitFor: ['build-web']
    args:
      - push
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_WEB_SERVICE}'

  # ── Deploy web (public-facing) ──
  - id: deploy-web
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    waitFor: ['push-web']
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_WEB_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_WEB_SERVICE}:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=3000
      - --cpu=1
      - --memory=512Mi
      - --min-instances=${_WEB_MIN_INSTANCES}
      - --max-instances=${_WEB_MAX_INSTANCES}
      - --concurrency=40
      - --timeout=30s
      - --add-cloudsql-instances=overplanned-app:us-central1:overplanned-db
      - --set-env-vars=NODE_ENV=production
      - --set-secrets=DATABASE_URL=DATABASE_URL:latest,NEXTAUTH_SECRET=NEXTAUTH_SECRET:latest,NEXTAUTH_URL=NEXTAUTH_URL:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,SENTRY_DSN=SENTRY_DSN:latest,STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest,RESEND_API_KEY=RESEND_API_KEY:latest,BETA_CODE=BETA_CODE:latest

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_WEB_SERVICE}:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_MEDIUM

timeout: 1200s
