# ── Overplanned Cloud Build — build + deploy to Cloud Run ─────────────
# Triggered on push to main. Builds web service, pushes to Artifact
# Registry, deploys to Cloud Run (public).
# ──────────────────────────────────────────────────────────────────────

substitutions:
  _REGION: us-central1
  _REPO: overplanned
  _WEB_SERVICE: overplanned-web
  _WEB_MIN_INSTANCES: '0'
  _WEB_MAX_INSTANCES: '10'

steps:
  # ── Run tests (parallel with cache pull + docker build) ──
  - id: test-web
    name: node:20
    waitFor: ['-']
    entrypoint: bash
    args:
      - -c
      - npm ci && cd apps/web && npx vitest run --reporter=dot --maxWorkers=2

  # ── Pull cache image (best-effort, parallel with tests) ──
  - id: pull-cache
    name: gcr.io/cloud-builders/docker
    waitFor: ['-']
    entrypoint: bash
    args:
      - -c
      - docker pull ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_WEB_SERVICE}:latest || true

  # ── Build web image (starts after cache pull, parallel with tests) ──
  # Uses bash entrypoint so secretEnv can pass SENTRY_DSN as a Docker build arg
  - id: build-web
    name: gcr.io/cloud-builders/docker
    waitFor: ['pull-cache']
    entrypoint: bash
    args:
      - -c
      - |
        docker build \
          -f Dockerfile.web \
          --cache-from ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_WEB_SERVICE}:latest \
          --build-arg NEXT_PUBLIC_SENTRY_DSN=$$SENTRY_DSN \
          -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_WEB_SERVICE}:${SHORT_SHA} \
          -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_WEB_SERVICE}:latest \
          .
    secretEnv: ['SENTRY_DSN']

  # ── Push web image (waits for both tests + build) ──
  - id: push-web
    name: gcr.io/cloud-builders/docker
    waitFor: ['test-web', 'build-web']
    args:
      - push
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_WEB_SERVICE}'

  # ── Start Cloud SQL proxy (needed for migrations) ──
  - id: start-sql-proxy
    name: gcr.io/cloud-builders/docker
    waitFor: ['test-web']
    entrypoint: bash
    args:
      - -c
      - |
        docker run -d --name cloud-sql-proxy --network cloudbuild \
          -v /workspace:/workspace \
          gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.3 \
          --address 0.0.0.0 --port 5432 \
          overplanned-app:us-central1:overplanned

  # ── ONE-SHOT: resolve failed migration (remove after successful deploy) ──
  - id: resolve-failed-migration
    name: node:20
    waitFor: ['start-sql-proxy']
    entrypoint: bash
    args:
      - -c
      - |
        for i in 1 2 3 4 5; do
          nc -z cloud-sql-proxy 5432 && break
          echo "Waiting for Cloud SQL proxy..."
          sleep 2
        done
        npx prisma@5.22.0 migrate resolve --rolled-back 20260226040000_prelaunch_behavioral_scaffolding --schema=packages/db/prisma/schema.prisma
    secretEnv: ['DATABASE_URL']

  # ── Run Prisma migrations (before deploy, after tests pass) ──
  - id: migrate-db
    name: node:20
    waitFor: ['resolve-failed-migration']
    entrypoint: bash
    args:
      - -c
      - |
        npx prisma migrate deploy --schema=packages/db/prisma/schema.prisma
    secretEnv: ['DATABASE_URL']

  # ── Deploy web (public-facing) ──
  - id: deploy-web
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    waitFor: ['push-web', 'migrate-db']
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_WEB_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_WEB_SERVICE}:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=3000
      - --cpu=1
      - --memory=512Mi
      - --min-instances=${_WEB_MIN_INSTANCES}
      - --max-instances=${_WEB_MAX_INSTANCES}
      - --concurrency=40
      - --timeout=30s
      - --cpu-boost
      - --add-cloudsql-instances=overplanned-app:us-central1:overplanned
      - --set-env-vars=NODE_ENV=production
      - --set-secrets=DATABASE_URL=DATABASE_URL:latest,NEXTAUTH_SECRET=NEXTAUTH_SECRET:latest,NEXTAUTH_URL=NEXTAUTH_URL:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,SENTRY_DSN=SENTRY_DSN:latest,STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest,RESEND_API_KEY=RESEND_API_KEY:latest,BETA_CODE=BETA_CODE:latest,DISCORD_WEBHOOK_URL=DISCORD_WEBHOOK_URL:latest

  # ── Notify Discord on successful deploy ──
  - id: notify-discord
    name: gcr.io/cloud-builders/curl
    waitFor: ['deploy-web']
    entrypoint: bash
    args:
      - -c
      - |
        curl -s -H "Content-Type: application/json" \
          -d "{\"content\":\"Deployed \`${SHORT_SHA}\` to production :rocket:\"}" \
          "$$DISCORD_WEBHOOK_URL"
    secretEnv: ['DISCORD_WEBHOOK_URL']

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/DATABASE_URL_TCP/versions/latest
      env: DATABASE_URL
    - versionName: projects/${PROJECT_ID}/secrets/DISCORD_WEBHOOK_URL/versions/latest
      env: DISCORD_WEBHOOK_URL
    - versionName: projects/${PROJECT_ID}/secrets/SENTRY_DSN/versions/latest
      env: SENTRY_DSN

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_WEB_SERVICE}:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_MEDIUM

timeout: 1200s
