"""
Subflow Tagger — V2 ML Pipeline Phase 1.2.

Assigns a ``subflow`` context string to a BehavioralSignal at creation time.
Subflows segment the user's decision-making context so the ML model can learn
distinct preference patterns per context (e.g. first-ever trip vs. repeat-city
traveler vs. group-split scenario).

Priority ordering (rarest / most-specific context wins)
--------------------------------------------------------
 1  first_creation_rejection   — first-ever trip, user rejected a slot
 2  itinerary_alteration_date  — date shift detected in the current session
 3  itinerary_alteration_swap  — slot swap detected in the current session
 4  itinerary_alteration_category — 2+ same-category removals in session
 5  group_split                — group trip with an active split event
 6  repeat_city                — user has a prior completed trip to the same city
 7  group_ranking              — group trip ranking context (no split active)
 8  hllm_rerank                — HLLM subflow was triggered for this signal
 9  offline_pivot              — signal generated by the pivot system
10  onthefly_add               — user added an activity mid-trip
11  core_ranking               — default fallback (plain solo ranking context)

Design notes
------------
- The tagger is a pure function — no I/O, no DB calls.
- Context dict keys are camelCase to mirror the rest of the codebase dicts.
- Returns None only when the signal dict is entirely empty; callers should
  fall back to "core_ranking" themselves when None is returned.
"""

from __future__ import annotations

from typing import Literal

# ---------------------------------------------------------------------------
# Types
# ---------------------------------------------------------------------------

SubflowTag = Literal[
    "first_creation_rejection",
    "itinerary_alteration_date",
    "itinerary_alteration_swap",
    "itinerary_alteration_category",
    "group_split",
    "repeat_city",
    "group_ranking",
    "hllm_rerank",
    "offline_pivot",
    "onthefly_add",
    "core_ranking",
]

# Priority-ordered list of (context_key, subflow_value) pairs.
# The tagger walks this list and returns on the first truthy key.
_PRIORITY_CHECKS: list[tuple[str, str]] = [
    ("firstCreationRejection", "first_creation_rejection"),
    ("itineraryAlterationDate", "itinerary_alteration_date"),
    ("itineraryAlterationSwap", "itinerary_alteration_swap"),
    ("itineraryAlterationCategory", "itinerary_alteration_category"),
    ("groupSplit", "group_split"),
    ("repeatCity", "repeat_city"),
    ("groupRanking", "group_ranking"),
    ("hllmRerank", "hllm_rerank"),
    ("offlinePivot", "offline_pivot"),
    ("ontheflyAdd", "onthefly_add"),
]

_DEFAULT_SUBFLOW: str = "core_ranking"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def tag_subflow(signal: dict, context: dict) -> str | None:
    """
    Determine the subflow tag for a BehavioralSignal.

    Walks a priority-ordered list of context keys; the first truthy key wins.
    Falls back to ``core_ranking`` when no context key matches.
    Returns None only when both ``signal`` and ``context`` are falsy/empty,
    which callers may treat as ``core_ranking``.

    Args:
        signal:  BehavioralSignal dict. Used for signal-level flags such as
                 ``offlinePivot`` and ``ontheflyAdd`` that are set at signal
                 creation time rather than in the broader session context.
        context: Session/trip context dict. Supported keys (all optional):

                 firstCreationRejection  bool  — True if this is the user's
                                                 first ever trip and they
                                                 rejected a generated slot
                 itineraryAlterationDate bool  — date shift detected in session
                 itineraryAlterationSwap bool  — slot swap detected in session
                 itineraryAlterationCategory bool — 2+ same-category removals
                 groupSplit              bool  — group trip with active split
                 repeatCity             bool  — user visited this city before
                 groupRanking           bool  — group trip without active split
                 hllmRerank             bool  — HLLM subflow triggered
                 offlinePivot           bool  — pivot system generated signal
                 ontheflyAdd            bool  — mid-trip user-added activity

    Returns:
        A SubflowTag string, or None if both dicts are empty/None.
    """
    if not signal and not context:
        return None

    # Merge signal-level flags into the context lookup dict.
    # Signal flags take the same priority position as context flags — the
    # priority list controls ordering, not whether the value came from
    # signal or context.
    merged: dict = {}
    if context:
        merged.update(context)
    if signal:
        merged.update(signal)

    for key, subflow in _PRIORITY_CHECKS:
        if merged.get(key):
            return subflow

    return _DEFAULT_SUBFLOW
